"""baseline phase1 schema

Revision ID: 659df6833a92
Revises: 
Create Date: 2026-09-19 18:11:16.913624

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '659df6833a92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('capabilities',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_kind'), 'capabilities', ['kind'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('vendor', sa.String(length=80), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('paired_encrypted', sa.Text(), nullable=True),
    sa.Column('preview', sa.String(length=100), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_fingerprint'), 'credentials', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_credentials_review_status'), 'credentials', ['review_status'], unique=False)
    op.create_index(op.f('ix_credentials_type'), 'credentials', ['type'], unique=False)
    op.create_index(op.f('ix_credentials_verification_status'), 'credentials', ['verification_status'], unique=False)
    op.create_table('ignore_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=30), nullable=False),
    sa.Column('scope_value', sa.String(length=300), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_records',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('vendor', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('license', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('verifier_id', sa.String(length=80), nullable=True),
    sa.Column('file_sha', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_records_type'), 'rule_records', ['type'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('collector_key', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_credential_id'), 'review_logs', ['credential_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('interval_sec', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('verifier_id', sa.String(length=80), nullable=False),
    sa.Column('requested_by', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_jobs_credential_id'), 'verification_jobs', ['credential_id'], unique=False)
    op.create_index(op.f('ix_verification_jobs_status'), 'verification_jobs', ['status'], unique=False)
    op.create_table('cursors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('cursor_key', sa.String(length=200), nullable=False),
    sa.Column('cursor_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'cursor_key', name='uq_cursor_task_key')
    )
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('stats_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('verifier_id', sa.String(length=80), nullable=False),
    sa.Column('verifier_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['verification_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_credential_id'), 'verification_results', ['credential_id'], unique=False)
    op.create_table('source_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('origin_url', sa.String(length=500), nullable=True),
    sa.Column('repo', sa.String(length=300), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('version_id', sa.String(length=200), nullable=False),
    sa.Column('version_kind', sa.String(length=30), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_truncated', sa.Boolean(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_source', sa.String(length=200), nullable=True),
    sa.Column('published_confidence', sa.String(length=20), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('detection_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['scan_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'version_id', 'path', 'content_hash', name='uq_content_version')
    )
    op.create_table('occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('origin_url', sa.String(length=500), nullable=True),
    sa.Column('repo', sa.String(length=300), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.String(length=200), nullable=True),
    sa.Column('version_kind', sa.String(length=30), nullable=False),
    sa.Column('context_masked', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('location_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['source_contents.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scan_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id', 'location_hash', name='uq_occurrence_cred_loc')
    )
    op.create_index(op.f('ix_occurrences_credential_id'), 'occurrences', ['credential_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occurrences_credential_id'), table_name='occurrences')
    op.drop_table('occurrences')
    op.drop_table('source_contents')
    op.drop_index(op.f('ix_verification_results_credential_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_table('scan_runs')
    op.drop_table('cursors')
    op.drop_index(op.f('ix_verification_jobs_status'), table_name='verification_jobs')
    op.drop_index(op.f('ix_verification_jobs_credential_id'), table_name='verification_jobs')
    op.drop_table('verification_jobs')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_review_logs_credential_id'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_table('sources')
    op.drop_index(op.f('ix_rule_records_type'), table_name='rule_records')
    op.drop_table('rule_records')
    op.drop_table('ignore_rules')
    op.drop_index(op.f('ix_credentials_verification_status'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_type'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_review_status'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_fingerprint'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_capabilities_kind'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
